<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PbacResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array<string, mixed>
     */
    public function toArray($request)
    {
        return [
            'ReportedDate' => $this->reported_date,
            'BL' => $this->q3a,
            'Spot' => $this->q3b,
            'Mens' => $this->q3c,
            'FirstDay' => $this->q3d,
            'PadL' => $this->q4a,
            'PadM' => $this->q4b,
            'PadS' => $this->q4c,
            'TamL' => $this->q4d,
            'TamM' => $this->q4e,
            'TamS' => $this->q4f,
            'Pain' => $this->q5a,
            'PainL1' => $this->q5b,
            'PainL2' => $this->q5c,
            'PainL3' => $this->q5d,
            'PainL4' => $this->q5e,
            'PainL5' => $this->q5f,
            'PainL6' => $this->q5g,
            'PainL7' => $this->q5h,
            'PainL8' => $this->q5i,
            'PainL9' => $this->q5j,
            'PainL10' => $this->q5k,
            'PainL11' => $this->q5l,
            'PainL12' => $this->q5m,
            'PainL13' => $this->q5n,
            'PainL14' => $this->q5o,
            'PainL15' => $this->q5p,
            'PainTrig1' => $this->q6a,
            'PainTrig2' => $this->q6b,
            'PainTrig3' => $this->q6c,
            'PainTrig4' => $this->q6d,
            'PainTrig5' => $this->q6e,
            'PainTrig6' => $this->q6f,
            'PainBig' => $this->q7a,
            'PainType' => $this->q7b,
            'PainPCM' => $this->q8a,
            'PainDiclo' => $this->q8b,
            'PainNapr' => $this->q8c,
            'PainTram' => $this->q8d,
            'PainOxy' => $this->q8e,
            'PainMedOth' => $this->q8f,
            'work' => $this->q9a,
            'school' => $this->q9b,
            'sport' => $this->q9c,
            'moving' => $this->q9d,
            'sleeping' => $this->q9e,
            'sitting' => $this->q9f,
            'other' => $this->q9g,
            'QoL' => $this->q10,
            'Mood' => $this->q11,
            'Fatique' => $this->q12,
            'UrineFreq' => $this->q13a,
            'UrineNoc' => $this->q13b,
            'UrinePain' => $this->q13c,
            'UrineBlood' => $this->q13d,
            'UrinePainSco' => $this->q13e,
            'StoolFreq' => $this->q14a,
            'StoolPain' => $this->q14b,
            'StoolBlood' => $this->q14c,
            'StoolCons' => $this->q14d,
            'StoolNight' => $this->q14e,
            'SexPain' => $this->q15,
            'SexBlood' => $this->q16a,
            'SexDis' => $this->q16b,
            'SexSat' => $this->q16c,
            'SleepH' => $this->q17a,
            'SleepDo' => $this->q17b,
            'SleepUp' => $this->q17c,
            'SleepTr' => $this->q17d,
            'SleepRes' => $this->q17e,
            'SleepWake' => $this->q17f,
            'SleepSatis' => $this->q17g,
            'Exer30' => $this->q18a,
            'Exer60' => $this->q18b,
            'Exer90' => $this->q18c,
            'ExerRelx' => $this->q18d,
            'ExerLimi' => $this->q18e,
            'Diet1' => $this->q19a,
            'Diet2' => $this->q19b,
            'Diet3' => $this->q19c,
            'Diet4' => $this->q19d,
            'Diet5' => $this->q19e,
            'Diet6' => $this->q19f,
            'Diet7' => $this->q19g,
            'Diet8' => $this->q19h,
            'Diet9' => $this->q19i,
            'pbacScorePerDay' => $this->pbac_score_per_day,
            'painScorePerDay' => $this->pain_score_per_day,
            'spottingYesNo' => $this->spotting_yes_no,
            'influenceFactor' => $this->influence_factor,
            'painMedication' => $this->pain_medication,
            'qualityOfLife' => $this->quality_of_life,
            'energyLevel' => $this->energy_level,
            'complaintsWithDefecation' => $this->complaints_with_defecation,
            'complaintsWithUrinating' => $this->complaints_with_urinating,
            'qualityOfSleep' => $this->quality_of_sleep,
            'exercise' => $this->exercise,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
