<?php

namespace App\Http\Requests\Api\Pbac;

use Illuminate\Foundation\Http\FormRequest;

class StoreOrUpdatePbacRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'ReportedDate' => 'required|date',
            'CreatedDate' => 'nullable|date',
            'BL' => 'nullable|integer',
            'Spot' => 'nullable|integer',
            'Mens' => 'nullable|integer',
            'FirstDay' => 'nullable|integer',
            'PadL' => 'nullable|integer',
            'PadM' => 'nullable|integer',
            'PadS' => 'nullable|integer',
            'TamL' => 'nullable|integer',
            'TamM' => 'nullable|integer',
            'TamS' => 'nullable|integer',
            'Pain' => 'nullable|integer',
            'PainL1' => 'nullable|integer',
            'PainL2' => 'nullable|integer',
            'PainL3' => 'nullable|integer',
            'PainL4' => 'nullable|integer',
            'PainL5' => 'nullable|integer',
            'PainL6' => 'nullable|integer',
            'PainL7' => 'nullable|integer',
            'PainL8' => 'nullable|integer',
            'PainL9' => 'nullable|integer',
            'PainL10' => 'nullable|integer',
            'PainL11' => 'nullable|integer',
            'PainL12' => 'nullable|integer',
            'PainL13' => 'nullable|integer',
            'PainL14' => 'nullable|integer',
            'PainL15' => 'nullable|integer',
            'PainTrig1' => 'nullable|integer',
            'PainTrig2' => 'nullable|integer',
            'PainTrig3' => 'nullable|integer',
            'PainTrig4' => 'nullable|integer',
            'PainTrig5' => 'nullable|integer',
            'PainTrig6' => 'nullable|integer',
            'PainBig' => 'nullable|integer',
            'PainType' => 'nullable|integer',
            'PainPCM' => 'nullable|integer',
            'PainDiclo' => 'nullable|integer',
            'PainNapr' => 'nullable|integer',
            'PainTram' => 'nullable|integer',
            'PainOxy' => 'nullable|integer',
            'PainMedOth' => 'nullable|integer',
            'work' => 'nullable|integer',
            'school' => 'nullable|integer',
            'sport' => 'nullable|integer',
            'moving' => 'nullable|integer',
            'sleeping' => 'nullable|integer',
            'sitting' => 'nullable|integer',
            'other' => 'nullable|integer',
            'QoL' => 'nullable|integer',
            'Mood' => 'nullable|integer',
            'Fatique' => 'nullable|integer',
            'UrineFreq' => 'nullable|integer',
            'UrineNoc' => 'nullable|integer',
            'UrinePain' => 'nullable|integer',
            'UrineBlood' => 'nullable|integer',
            'UrinePainSco' => 'nullable|integer',
            'StoolFreq' => 'nullable|integer',
            'StoolPain' => 'nullable|integer',
            'StoolBlood' => 'nullable|integer',
            'StoolCons' => 'nullable|integer',
            'StoolNight' => 'nullable|integer',
            'SexPain' => 'nullable|integer',
            'SexBlood' => 'nullable|integer',
            'SexDis' => 'nullable|integer',
            'SexSat' => 'nullable|integer',
            'SleepH' => 'nullable|integer',
            'SleepDo' => 'nullable|string',
            'SleepUp' => 'nullable|string',
            'SleepTr' => 'nullable|integer',
            'SleepRes' => 'nullable|integer',
            'SleepWake' => 'nullable|integer',
            'SleepSatis' => 'nullable|integer',
            'Exer30' => 'nullable|integer',
            'Exer60' => 'nullable|integer',
            'Exer90' => 'nullable|integer',
            'ExerRelx' => 'nullable|integer',
            'ExerLimi' => 'nullable|integer',
            'Diet1' => 'nullable|integer',
            'Diet2' => 'nullable|integer',
            'Diet3' => 'nullable|integer',
            'Diet4' => 'nullable|integer',
            'Diet5' => 'nullable|integer',
            'Diet6' => 'nullable|integer',
            'Diet7' => 'nullable|integer',
            'Diet8' => 'nullable|integer',
            'Diet9' => 'nullable|integer',
        ];
    }

    /**
     * Body parameters for PBAC store/update endpoints.
     */
    public function bodyParameters(): array
    {
        return [
            'ReportedDate' => [
                'description' => 'The date the PBAC is reported for.',
                'example' => '2024-07-02',
                'required' => true,
                'type' => 'date',
            ],
            'CreatedDate' => [
                'description' => 'The date the PBAC record was created (optional, defaults to today if omitted).',
                'example' => '2025-07-04',
                'required' => false,
                'type' => 'date',
            ],
            'BL' => ['description' => 'Blood loss', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Spot' => ['description' => 'Spotting', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'Mens' => ['description' => 'Menstrual blood loss', 'example' => 2, 'required' => false, 'type' => 'integer'],
            'FirstDay' => ['description' => 'First day period', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'PadL' => ['description' => 'Pads large', 'example' => 2, 'required' => false, 'type' => 'integer'],
            'PadM' => ['description' => 'Pads medium', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'PadS' => ['description' => 'Pads small', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'TamL' => ['description' => 'Tampon large', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'TamM' => ['description' => 'Tampon medium', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'TamS' => ['description' => 'Tampon small', 'example' => 1, 'required' => false, 'type' => 'integer'],
            'Pain' => ['description' => 'Pain', 'example' => 3, 'required' => false, 'type' => 'integer'],
            'PainL1' => ['description' => 'Pain location umbilical', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL2' => ['description' => 'Pain location left umbilical', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL3' => ['description' => 'Pain location right umbilical', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL4' => ['description' => 'Pain location bladder', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL5' => ['description' => 'Pain location left groin', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL6' => ['description' => 'Pain location right groin', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL7' => ['description' => 'Pain location left leg', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL8' => ['description' => 'Pain location right leg', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL9' => ['description' => 'Pain location upper back', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL10' => ['description' => 'Pain location back', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL11' => ['description' => 'Pain location left buttock', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL12' => ['description' => 'Pain location right buttock', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL13' => ['description' => 'Pain location left back leg', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL14' => ['description' => 'Pain location right back leg', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainL15' => ['description' => 'Pain location Headache', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTrig1' => ['description' => 'Pain triger exercise', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTrig2' => ['description' => 'Pain trigger peeing', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTrig3' => ['description' => 'Pain trigger def', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTrig4' => ['description' => 'Pain trigger seks', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTrig5' => ['description' => 'Pain trigger food', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTrig6' => ['description' => 'Pain trigger other', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainBig' => ['description' => 'Most problematic pain', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainType' => ['description' => 'Type of pain', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainPCM' => ['description' => 'Pain killers PCM', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainDiclo' => ['description' => 'Pain kiler Diclofenac', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainNapr' => ['description' => 'Pain killer Naproxen', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainTram' => ['description' => 'Pain killer tramadol', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainOxy' => ['description' => 'Pain killer Oxynorm', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'PainMedOth' => ['description' => 'Pain killer other', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'work' => ['description' => 'Influence Work', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'school' => ['description' => 'Influence School', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'sport' => ['description' => 'Influence Sport', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'moving' => ['description' => 'Influence Moving', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'sleeping' => ['description' => 'Influence Sleeping', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'sitting' => ['description' => 'Influence Sitting', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'other' => ['description' => 'Influence Other', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'QoL' => ['description' => 'Quality of life', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Mood' => ['description' => 'Mood', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Fatique' => ['description' => 'Fatigue', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'UrineFreq' => ['description' => 'Urine frequency', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'UrineNoc' => ['description' => 'Urine nocturia', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'UrinePain' => ['description' => 'Urine pain', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'UrineBlood' => ['description' => 'Urine blood', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'UrinePainSco' => ['description' => 'Urine pain score', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'StoolFreq' => ['description' => 'Stool frequency', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'StoolPain' => ['description' => 'Stool pain', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'StoolBlood' => ['description' => 'Stool blood', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'StoolCons' => ['description' => 'Stool consistency', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'StoolNight' => ['description' => 'Stool at night', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SexPain' => ['description' => 'Seks Pain', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SexBlood' => ['description' => 'Seks blood loss', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SexDis' => ['description' => 'Seks discomfort', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SexSat' => ['description' => 'Seks satisfaction', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SleepH' => ['description' => 'Sleep hours', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SleepDo' => ['description' => 'Time went to bed (HH:MM, e.g., 23:45)', 'example' => '23:45', 'required' => false, 'type' => 'string'],
            'SleepUp' => ['description' => 'Time woke up (HH:MM, e.g., 06:30)', 'example' => '06:30', 'required' => false, 'type' => 'string'],
            'SleepTr' => ['description' => 'Sleep falling a sleep', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SleepRes' => ['description' => 'Sleep rested', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SleepWake' => ['description' => 'Sleep waking-up', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'SleepSatis' => ['description' => 'Sleep satisfaction', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Exer30' => ['description' => 'Exercise less 30min', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Exer60' => ['description' => 'Exercise 30-60min', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Exer90' => ['description' => 'Exercise more 60min', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'ExerRelx' => ['description' => 'Exercise relaxing', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'ExerLimi' => ['description' => 'Exercise limitations', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet1' => ['description' => 'Processed food', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet2' => ['description' => 'Refined Sugars', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet3' => ['description' => 'Red meat', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet4' => ['description' => 'Dairy', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet5' => ['description' => 'Gluten', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet6' => ['description' => 'Soy', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet7' => ['description' => 'Coffee', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet8' => ['description' => 'Alcohol', 'example' => 0, 'required' => false, 'type' => 'integer'],
            'Diet9' => ['description' => 'Fast food', 'example' => 0, 'required' => false, 'type' => 'integer'],
        ];
    }
}
